### ISSUE TITLE
[9 пріоритет] Процедура была переведена в статус "Complete", до того, как были переведены все контракты в статус "active"

### ISSUE THREAD

**Issue by vmaksymiv** [openprocurement/openprocurement.tender.limited#52]
Есть мультилотовая переговорная процедура (2 лота) https://lb.api-sandbox.openprocurement.org/api/2.3/tenders/1bceea1becfe4166b4703d46de14d031 
Процедура была переведена в статус "Complete", до того, как были переведены все контракты в статус "active"
Был отправлен запрос на изменение статуса контракта по эворду для первого лота
После смены статуса, автоматически меняется статус процедуры в "Complete"
Соответственно мы не можем изменить статус контракта по эворду второго лота

ref:  http://prozorro.worksection.ua/project/140997/4083807/

**Comment by Krokop** [comment]
Виправив, прибрав залишок коду від старої перевірки, додав тести.
